### ISSUE TITLE
Retry backup spool changes request on failure

### ISSUE THREAD

**Issue by smithsz** [cloudant/couchbackup#100]
A failure in the spool changes request will terminated the backup process.
https://github.com/cloudant/couchbackup/blob/master/includes/spoolchanges.js#L74

We should retry this request on failure using a suitable `since` parameter.

**Comment by smithsz** [comment]
wip branch, https://github.com/cloudant/couchbackup/tree/100-retry-changes-spooler-on-failure

**Comment by smithsz** [comment]
I propose we abstract this retrying logic in cloudant-follow (a dependancy of nodejs-cloudant).
Raised new issue to support `feed=normal` changes requests - https://github.com/cloudant-labs/cloudant-follow/issues/3.

**Comment by ricellis** [comment]
Since #184 and #188 the nodejs-cloudant `retry` plugin is enabled. This will prevent the process terminating on a failure to spool changes, but it retires the whole request, rather than resuming with a `since` so I'll leave this ticket open.

**Comment by ricellis** [comment]
This was done in #412 - since then the changes feed is split over multiple requests with a retry available on each one, so the effective behaviour is the same as resuming with a since after an error.
