### ISSUE TITLE
Ensure multiple backups don't trample on each other

### ISSUE THREAD

**Issue by smithsz** [cloudant/couchbackup#110]
Implement a file lock to prevent multiple backups (likely badly configured) from using the same log file.

**Comment by ricellis** [comment]
After looking at #227 recently I think this is a side effect of the way default log file name is generated.
For example if you do:
```js
const backup = require('@cloudant/couchbackup').backup;
```
Then every time the `backup` function is called without a specific log file option it will have the same default log file.
