### ISSUE TITLE
Feature: backup all databases

### ISSUE THREAD

**Issue by homerjam** [cloudant/couchbackup#144]
In my scenario I'd like to setup a cron job to periodically backup all the databases in my account - including new ones that I create.

**Comment by ricellis** [comment]
Maybe something like this:
```sh
#!/bin/sh

DAYSTAMP=`date +%y%m%d`
for db in $(curl -Ss ${COUCH_URL}/_all_dbs | jq -r '.[] | @uri'); do
  couchbackup --db ${db} > ${db}_${DAYSTAMP}.backup
done
```

**Comment by homerjam** [comment]
Woah. That looks cool, I'll try it out.

**Comment by homerjam** [comment]
Bingo.

**Comment by jay-b** [comment]
> Maybe something like this:
> 
> ```shell
> #!/bin/sh
> 
> DAYSTAMP=`date +%y%m%d`
> for db in $(curl -Ss ${COUCH_URL}/_all_dbs | jq -r '.[] | @uri'); do
>   couchbackup --db ${db} > ${db}_${DAYSTAMP}.backup
> done
> ```

When I try this my txt files are empty, any idea why?

**Comment by ricellis** [comment]
@jay-b no idea, if you run the command for one database alone does it work? are there no error messages at all?

**Comment by jay-b** [comment]
If I run:
`couchbackup --url https://myusername:mypassword@myhost.cloudant.com --db db_Name > backup.txt`

I get the contents of the db in a .txt file as expected.

But if I run:
`COUCH_URL=https://myusername:mypassword@myhost.cloudant.com`
`for db in $(curl -Ss ${COUCH_URL}/_all_dbs | jq -r '.[] | @uri'); do
  couchbackup --db ${db} > ${db}_.backup.txt`
`done`

I get a blank .txt file and the following error:
`Streaming changes to disk:
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^`

`Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14`

**Comment by ricellis** [comment]
Looks like the `COUCH_URL` environment variable isn't visible to the backup command (it's defaulting to localhost 5984) - I think when I did this originally I'd exported it beforehand. So I think you'll just need to figure out the shell scripting needed to make the `COUCH_URL` env var visible to your `couchbackup` command.
