### ISSUE TITLE
help request - restore is not restoring

### ISSUE THREAD

**Issue by cellog** [cloudant/couchbackup#151]
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) that are affected by this issue.
- Node.js version.
- A sample of the code or command line statement that demonstrates the issue.

I am pretty sure I am not understanding how to do this: do I need to erase the database in order for restore to be fully byte-for-byte the same on restore?  I'm getting no changes after restore.

This is time-critical: production db is corrupt.

Thanks for any help

**Comment by ricellis** [comment]
@cellog 
For `couchrestore` you should direct it to a new empty database. It will not create a new database for you.

**Comment by cellog** [comment]
thanks for the fast reply, I'll try that

**Comment by cellog** [comment]
This worked. I had to also wipe the local databases in every client's pouchdb indexeddb database and force a restore in order to remove the conflicts and deletions I kept getting.  But it worked eventually!
