### ISSUE TITLE
Cannot restore backup from database that contained attachments

### ISSUE THREAD

**Issue by accursoft** [cloudant/couchbackup#161]
I used couchbackup 2.0.0 to backup a database that contains attachments. (It's driven from a proprietary program, so I don't know the exact couchbackup methods and parameters that were used.) I was not expecting attachments to be backed up or restored, but I could not restore the database at all:
`error: Restore for DB ... failedHTTPFatalError: 412 Precondition Failed: POST .../_bulk_docs - Error: missing_stub, Reason: Invalid attachment stub in ... for ...`
Is this expected? Is there any workaround?

**Comment by ricellis** [comment]
The tool does not support attachments. A database containing documents with attachments will include attachment metadata within the documents. Sending this data during a restore, but without the attachments causes this error.

We will clarify the documentation to make it more clear that "couchbackup does not backup attachments" doesn't mean attachments are just skipped, but means it isn't valid to use the tool on databases with attachments.
