### ISSUE TITLE
DB restore Error: too_large, Reason: the request entity is too large

### ISSUE THREAD

**Issue by tsghosh** [cloudant/couchbackup#164]
using "@cloudant/couchbackup":"2.0.0"

Hi I am trying to restore a earlier a sample database , _hitting 413 Request Entity Too Large: POST https://xxyyzz.cloudant.com/r_history/_bulk_docs - Error: too_large, Reason: the request entity is too large_

File size is 1.35 MB only 

Any reason for this unusual behaviour? Are any additional settings required?

sample code:
### couchbackup.restore(fs.createReadStream(file_path),dest_url,{parallelism: 2},function(err, ok) {
                    if (err) {
                        console.log('Error in DB['+dbname+'] Restore '+err);
                        callback(err,null);
                    } else {
                        callback(null,ok);
                    }
                });

**Comment by smithsz** [comment]
Hi @tsghosh,
Please note that the maximum request body size to an API request for Cloudant is 1MB. You will receive a 413 response code stating “the request entity is too large” if you exceed this.
Have you tried reducing the `--buffer-size` parameter? The default is 500.
Thanks.

**Comment by tsghosh** [comment]
Thanks
