### ISSUE TITLE
Out of memory during restore

### ISSUE THREAD

**Issue by pulkitanchalia** [cloudant/couchbackup#170]
I ran couchrestore command to restore database, got out of memory error.

Size of DB to be restored = 1 GB

Is there any way to pass large memory allocation parameter?

PS D:\mytest> cat .\s3-upload.json | couchrestore --db s3-upload
================================================================================
Performing restore on http://localhost:5984/s3-upload using configuration:
{
  "bufferSize": 500,
  "parallelism": 5
}
================================================================================
Program 'couchrestore.cmd' failed to execute: Exception of type 'System.OutOfMemoryException' was thrown.
At line:1 char:36
+ cat .\s3-upload.json | couchrestore <<<<  --db s3-upload.
At line:1 char:1
+  <<<< cat .\s3-upload.json | couchrestore --db s3-upload
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by ricellis** [comment]
In future please be sure to complete the template when raising an issue, it helps us to respond to your request more effectively.

You have two options:
1. Reduce the `bufferSize` and/or `parallelism` to reduce the number of documents that will need to be in memory at any one time
2. Increase the memory available to the `couchrestore` Node.js application. There are different to do this depending on if you want to install some helper modules or tweak the command that runs `couchrestore`. An example is: `node --max_old_space_size=<size in MB> /path/to/your/couchbackup/bin/couchrestore.bin.js`

**Comment by tomblench** [comment]
closing, no further action

**Comment by tomblench** [comment]
@pulkitanchalia please re-open if you are still experiencing issues
