### ISSUE TITLE
Flag for Couch < 2.0 ?

### ISSUE THREAD

**Issue by wmbutler** [cloudant/couchbackup#175]
Please include the following information in your ticket:

I am running Cloudant 1.0.2 and backups are failing with this script. Log file is getting populated, but not the backup file. Is there a flag to specify 1.0 Couch Databases?

```
/usr/local/bin/couchbackup --url $URL --log $BASE/$DIR/$DATABASE.log --db $DATABASE > $BASE/$DIR/$DATABASE.json
```

**Comment by tomblench** [comment]
@wmbutler that seems like an unusual version number, do you mean [Cloudant Local](https://www.ibm.com/uk-en/marketplace/cloudant-local)? It's confusing because Cloudant Local is versioned differently to CouchDB.

Our [requirements](https://github.com/cloudant/couchbackup#requirements) state CouchDB 2.0 or higher is required.

In reality, the main requirement is the `bulk_get` endpoint, which I think is present in Cloudant Local.

**Comment by wmbutler** [comment]
When running against cloudant 1.0.4, with the above command, this it what my backups look like:

```drwxrwxr-x 2 ubuntu ubuntu       4096 Jan  4 16:16 .
drwxrwxr-x 4 ubuntu ubuntu       4096 Jan  4 16:15 ..
-rw-rw-r-- 1 ubuntu ubuntu   14258208 Jan  4 07:55 adventhp-20160830.log
-rw-rw-r-- 1 ubuntu ubuntu          0 Jan  4 07:54 adventhp-20160830.txt
-rw-rw-r-- 1 ubuntu ubuntu  327505205 Jan  4 08:05 chbva-20160830.log
-rw-rw-r-- 1 ubuntu ubuntu          0 Jan  4 07:55 chbva-20160830.txt
-rw-rw-r-- 1 ubuntu ubuntu 4481353715 Jan  4 13:43 chdrg-20160830.log
-rw-rw-r-- 1 ubuntu ubuntu          0 Jan  4 11:19 chdrg-20160830.txt
-rw-rw-r-- 1 ubuntu ubuntu  268639979 Jan  4 16:21 medreview.log
-rw-rw-r-- 1 ubuntu ubuntu          0 Jan  4 16:16 medreview.txt
-rw-rw-r-- 1 ubuntu ubuntu        632 Jan  4 04:19 template.log
-rw-rw-r-- 1 ubuntu ubuntu          0 Jan  4 04:19 template.txt```

**Comment by tomblench** [comment]
@wmbutler can you clarify where these version numbers are from, is this Cloudant Local?

**Comment by wmbutler** [comment]
Sorry, it's actually 1.0.2:

https://butler.cloudant.com/

**Comment by tomblench** [comment]
@wmbutler OK thanks, sorry for the confusion, I understand now.

That's quite an old version of the Cloudant service and it doesn't support the `bulk_get` endpoint which is required to use couchbackup.

If you need to use couchbackup you will need to talk to Cloudant support about upgrading your cluster.

**Comment by wmbutler** [comment]
Well,

It worked until a week ago. I'm in the process of migrating to a new cluster.

**Comment by tomblench** [comment]
@wmbutler can you grep your log files for "Database does not support /_bulk_get endpoint"? We should fail gracefully when `_bulk_get` is not available and you should see that message.
