### ISSUE TITLE
When will there be a supported version that addresses https://nodesecurity.io/advisories/534 ?

### ISSUE THREAD

**Issue by alexwood** [cloudant/couchbackup#178]
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) that are affected by this issue.
2.0.0 (LATEST)
- Node.js version.
ALL
- A sample of the code or command line statement that demonstrates the issue.
N/A

Using latest published version of https://www.npmjs.com/package/@cloudant/couchbackup which is 2.0.0

Scans show this is subject to https://nodesecurity.io/advisories/534  due to version of debug module requried. (https://github.com/cloudant/couchbackup/blob/95b0c5a1cc7ee0efe1f2b481cddf7b2348e0cfb5/package.json#L25)

I see latest snapshot has addressed this
https://github.com/cloudant/couchbackup/blob/master/package.json#L25

**can you please advise when this will be available in a supported version ?**

**Comment by tomblench** [comment]
@alexwood we have just released 2.0.1 which includes this fix

**Comment by alexwood** [comment]
Wow that was quick :) thanks for the update.
