### ISSUE TITLE
Compressed _changes responses from server handled incorrectly

### ISSUE THREAD

**Issue by ricellis** [cloudant/couchbackup#196]
- couchbackup/couchrestore version(s) that are affected by this issue.
    * 2.x
- Node.js version.
    * Any
- A sample of the code or command line statement that demonstrates the issue.
   * couchbackup --url https://examples.cloudant.com --db animaldb

couchbackup 2.x uses the `Accept-Encoding: gzip` header. If the Cloudant server accepts that header and returns a compressed response the changes feed is not decompressed correctly. This results in the error:
```
ERROR: Changes request terminated before last_seq was sent
```

This is because the response stream is not decompressed automatically even though the body data on the request is, from [request](https://github.com/request/request#requestoptions-callback) documentation:
>gzip - if true, add an Accept-Encoding header to request compressed content encodings from the server (if not already present) and decode supported content encodings in the response. Note: Automatic decoding of the response content is performed on the body data returned through request (both through the request stream and passed to the callback function) but is not performed on the response stream (available from the response event) which is the unmodified http.IncomingMessage object which may contain compressed data. See example below.

**Comment by shimmerjs** [comment]
Why's this just cropping up now?  Have been using 2.x for automated backups and didn't have any issues until 2.1.0 was released

**Comment by ricellis** [comment]
@shimmerjs it is a coincidence, the bug exists in all 2.x versions of couchbackup, the Cloudant service was updated to compress responses, which is what exposed the bug.

**Comment by ricellis** [comment]
For interested parties this issue is being worked around in the Cloudant service pending the release of a fix so couchbackup should be working normally against Cloudant accounts.
