### ISSUE TITLE
Couchbackup utility reject Cloudant endpoint deployed with a self-signed certificate

### ISSUE THREAD

**Issue by gangchen03** [cloudant/couchbackup#202]
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) that are affected by this issue.
2.1.0

- Node.js version.
npm version 5.6.0
node.js version v8.9.4

- A sample of the code or command line statement that demonstrates the issue.
Run couchbackup against HTTPs based endpoint. 
`couchbackup --url "https://admin:orange@172.16.40.2:30087" --log backup.log --db "platform-db" > platform-db-backup.txt`
Got error:
`================================================================================
Performing backup on https://****:****@172.16.40.2:30087/platform-db using configuration:
{
  "bufferSize": 500,
  "log": "backup.log",
  "mode": "full",
  "parallelism": 5
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
ERROR: error happened in your connection`

We suspect it is issue with the utility reject self-signed certificate.

**Comment by ricellis** [comment]
You could try to modify your Node.js environment to trust your self-signed certificate, for example using the [`NODE_EXTRA_CA_CERTS` environment variable](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file).

**Comment by ricellis** [comment]
Closing as stale, re-open if there is further discussion needed.
