### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by wmbutler** [cloudant/couchbackup#214]
Please include the following information in your ticket:

- couchbackup/couchrestore version(s) that are affected by this issue.

2.2.0

- Node.js version.

9.2.1

- A sample of the code or command line statement that demonstrates the issue.
```
/usr/local/bin/couchbackup --url $URL --buffer-size $BUFFERSIZE --parallelism $PARALLELISM --mode $MODE --log $BASE/$DIR/$DATABASE.log --db $DATABASE > $BASE/$DIR/$DATABASE.json
```

When setting parallelism to > 10 I do not see additional processes running

![screen shot 2018-04-07 at 2 55 59 pm](https://user-images.githubusercontent.com/1254810/38459784-dfd81d56-3a73-11e8-82b0-f177992d46a5.png)

However, the log file seems to indicate that it's recognized my change

```
Backing up demo
================================================================================
Performing backup on https://****:****@******.cloudant.com/demo using configuration:
{
  "bufferSize": 4000,
  "log": "/home/backup/2018-04-07/demo.log",
  "mode": "shallow",
  "parallelism": 100
}
================================================================================
```

**Comment by smithsz** [comment]
Node.js is single threaded and runs in one process. 

The `--parallelism` flag is the number of HTTP requests to perform in parallel when performing a backup. This does not spawn additional OS processes.

In our experience you rarely benefit from setting `--parallelism` to more than 5. However, this is workload dependant so do carry out your own benchmarking.

Running `couchbackup` isn't computationally heavy. The time it takes to complete is bound by your network and I/O speeds. Therefore utilising more OS processes isn't going to improve things greatly here.

**Comment by wmbutler** [comment]
I still suspect that it doesn't add more than 10 threads. I did not notice a difference in speed when  raised it to 20 or 30. I would expect a multiplier effect with parallelism. I can only assume it's broken.

**Comment by wmbutler** [comment]
It's not network limits.  I'm going from AWS to Softlayer. I'm backing up a 200GB DB over a 1GB pipe.

**Comment by ricellis** [comment]
Sure, I should have been more clear I was referring to my sample data, which wasn't running on anything like that size of pipe. Regardless as was stated previously:

>Node.js is single threaded and runs in one process.
>...
>In our experience you rarely benefit from setting --parallelism to more than 5. However, this is workload dependant so do carry out your own benchmarking.

The parallelism spreads the HTTP fetch requests so that they don't block each other, but there is still computational work going on with processing/writing the received JSON that is not truly parallelized in a Node.js process. If you're not getting any speed increases with parallelism >10 then you've found the limit of your environment in one respect or another.
