### ISSUE TITLE
Unable to resume backup

### ISSUE THREAD

**Issue by jareware** [cloudant/couchbackup#218]
```
# couchbackup --version
2.2.0
# node -v
v8.2.1
```

First backup:

```
================================================================================
Performing backup on https://****:****@my-db.example.com/ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344 using configuration:
{
  "bufferSize": 1000,
  "log": "ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344.log",
  "mode": "full",
  "parallelism": 1
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Total batches received: 1 +527ms
  couchbackup:backup Total batches received: 2 +88ms
  couchbackup:backup Total batches received: 3 +90ms
  couchbackup:backup Written batch ID: 0 Total document revisions written: 1000 Time: 2.346 +2s
  couchbackup:backup Written batch ID: 1 Total document revisions written: 2000 Time: 3.846 +1s
  couchbackup:backup Written batch ID: 2 Total document revisions written: 2984 Time: 5.295 +1s
  couchbackup:backup Finished - Total document revisions written: 2984 +11ms
```

Check to see the remote doc count:

```
# curl -s 'https://****:****@my-db.example.com/ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344' | node -p 'JSON.parse(fs.readFileSync(0))' | grep doc_count
  doc_count: 2986,
```

Wait a while, run again:

```
# curl -s 'https://****:****@my-db.example.com/ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344' | node -p 'JSON.parse(fs.readFileSync(0))' | grep doc_count
  doc_count: 2991,
```

OK, the remote DB has *definitely* changed; back up again:

```
================================================================================
Performing backup on https://****:****@my-db.example.com/ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344 using configuration:
{
  "bufferSize": 1000,
  "log": "ca9d8d9c-d2e0-47b9-99e4-1d2d0f2ba344.log",
  "mode": "full",
  "parallelism": 1,
  "resume": true
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Finished - Total document revisions written: 0 +339ms
```

Nothing got written, and the backup files (txt & log) haven't changed.

Is this a bug, or am I just misunderstanding how the `--resume` option works?

**Comment by ricellis** [comment]
I'm afraid you're misunderstanding how the `--resume` option works.

The `--resume` option works for a backup that has finished spooling changes, but has not yet completed downloading all the necessary batches of documents.

I can see from your output above that your first backup has:
>couchbackup:backup Finished - Total document revisions written: 2984 +11ms

So the resume in your second backup command has no effect because the backup has already completed.

What you are looking for is _incremental_ backup, which is not available at this time. It is tracked in #11 (which I see you found and commented on). Seems like our documentation could use some improvement in this area.

**Comment by jareware** [comment]
Ah, good to know! And good that I checked before leaving the script running, thinking I'm always backed up. :>

Do you want a small PR for the docs change?

**Comment by smithsz** [comment]
Thanks @jareware. I'll update the docs for this.
