### ISSUE TITLE
Backup all databases of a client

### ISSUE THREAD

**Issue by tbrodbeck** [cloudant/couchbackup#313]
I am sorry, maybe its because I am new to this. But is there also also a way to backup all databases of a client at once?

**Comment by mojito317** [comment]
You can use a short script to call `_all_dbs` and iterate the result e.g. https://github.com/cloudant/couchbackup/issues/144#issuecomment-313072388.

**Comment by tbrodbeck** [comment]
Thanks for the input. I managed to do the same with python:
dbs = client.all_dbs()
for db in dbs:
    os.system('couchbackup --url "{}" --db {} > DBsBackup/{}Backup.xml'.format(url, db, db))
