### ISSUE TITLE
Clean up error handling

### ISSUE THREAD

**Issue by ricellis** [cloudant/couchbackup#32]
- couchbackup/couchrestore version(s) that are affected by this issue.
>1.4.0
- Node.js version.
>N/A
- A sample of the code or command line statement that demonstrates the issue.
>N/A

Refactor the error handling so that the API and internal functions only emit error events and do not write to `stderr`. This will avoid suppressing errors from being handled by API callers and also give API users complete control over the output.
The command line tooling (effectively an API user) should write to `stderr` when receiving the events. <-- I think this part was handled by #52 (but whoever picks this up should check)

We should also check for whether something calls the `callback(err)` or emits an `error` event and document the expected behaviour.

**Comment by smithsz** [comment]
Closely related to #103. I'll pick this one up too.

**Comment by smithsz** [comment]
After some discussion,
- an event emitter `error` will represent a non-fatal error
(will be printed to stderr in the CLI)
- a callback error will represent a fatal error
(will terminate the CLI with a suitable exit code)
