### ISSUE TITLE
couchbackup not working with shallow mode

### ISSUE THREAD

**Issue by wyattmw** [cloudant/couchbackup#339]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### Bug Description
After a recent update to node.js 12.8.2 (from node.js 12.16.1) our scripts that call couchbackup are seeing errors.  I have narrowed down the issue to shallow mode, because running the same command without "--mode shallow" works.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

From linux command line, run a shallow couchbackup:

/usr/local/node/bin/couchbackup --url https://user:password@hostname/ --buffer-size 5000 --mode shallow --db ngapi_permissions_pre

### 2. What you expect to happen
couchbackup completed.  You can see what happened when omitting the "--mode shallow" from the command:

```
/usr/local/node/bin/couchbackup --url https://user:password@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "log": "/tmp/tmp-32337S4S3JRNI4vnL",
  "mode": "full",
  "parallelism": 5,
  "requestTimeout": 120000,
  "resume": false
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Total batches received: 1 +223ms
```

### 3. What actually happened
With shallow mode option enabled, the following error occurred:

```
/usr/local/node/bin/couchbackup --url https://user:password@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre --mode shallow
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "mode": "shallow",
  "requestTimeout": 120000
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Invalid parameters
    at Object.<anonymous> (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:20:34)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/cloudant.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Emitted 'error' event at:
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:42:14
    at callbackOrRejectError (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:47:12)
    at Object.fetchDocs [as fetch] (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:649:16)
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:39:10
    at check (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2116:13)
    at doWhilst (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2119:16)
    at awaitable (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:208:32)
    at Object.doUntil (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2147:16)
    at module.exports (/usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:28:9)
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/app.js:251:26
```

## Environment details
couchbackup npm package version:   2.5.2
node.js version:   v12.18.2
OS:  RHEL 7.8

**Comment by wyattmw** [comment]
Did some additional testing and went back to node.js 12.16.1 and couchbackup 2.5.2.  Still failing as shown above.

Downgraded the couchbackup to 2.4.2, then 2.4.1 and 2.4.0  all with the following results:

```
/usr/local/node/bin/couchbackup --url https://user:password@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre --mode shallow
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "mode": "shallow",
  "requestTimeout": 120000
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
ERROR: Invalid parameters
```

I tried going back further to 2.3.1 and 2.3.0 of couchbackup and both of those worked correctly:

```
/usr/local/node/bin/couchbackup --url https://user:password@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre --mode shallow > test.out
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "log": "/tmp/tmp-30602clI505USoUeB.tmp",
  "mode": "shallow",
  "parallelism": 5
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Written batch ID: 0 Total document revisions written: 386 Time: 0.142 +399ms
  couchbackup:backup Finished - Total document revisions written: 386 +1ms
```

It's possible that during the node.js upgrade our automated processes updated the couchbackup plugin as well.  I can't say 100% sure though what version was installed prior to the node.js upgrade.

**Comment by wyattmw** [comment]
One last test, just to cover all the bases.   Using node.js 12.18.2 and couchbackup 2.3.1 also works.  So it was not the node.js version after all, but the upgrade of node.js that also updated the couchbackup version at the same time.

Output from the couchbackup command on node.js 12.18.2 and couckbackup 2.3.1:

```
 /usr/local/node/bin/couchbackup --url https://airtaimeryingedlyreannep:4d5fff2dbfd4975e7ec14184fe76f18261c5f121@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre --mode shallow > test.out
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "log": "/tmp/tmp-15845k7OctlX2Z5is.tmp",
  "mode": "shallow",
  "parallelism": 5
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Written batch ID: 0 Total document revisions written: 386 Time: 0.149 +380ms
  couchbackup:backup Finished - Total document revisions written: 386 +1ms
```

**Comment by bessbd** [comment]
Hi @wyattmw ,

Thank you for opening this ticket!
Looking at your last comment, it's like the issue is resolved now.
Is that correct?

**Comment by wyattmw** [comment]
It is resolved if I got back to v2.3.1 of the couchbackup npm.   However, it is still broken on every stable version from 2.4.0 onwards.

**Comment by rnewson** [comment]
@wyattmw please note we revoked the apikey you leaked in this ticket, we have notified the cluster admins as well.

**Comment by bessbd** [comment]
> It is resolved if I got back to v2.3.1 of the couchbackup npm. However, it is still broken on every stable version from 2.4.0 onwards.

For any broken environment, can you please include logs with debug (`DEBUG=couchbackup` [environment variable](https://github.com/cloudant/couchbackup#environment-variables)) enabled so that we get more information?

**Comment by wyattmw** [comment]
I put the `DEBUG=couchbackup` environment variable but didn't get any additional information:

```
[root@s11129 ~]# echo $DEBUG
couchbackup


[root@s11129 ~]# /usr/local/node/bin/couchbackup --url https://xxx:xxx@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 5000 --db ngapi_permissions_pre --mode shallow
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 5000,
  "mode": "shallow",
  "requestTimeout": 120000
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Invalid parameters
    at Object.<anonymous> (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:20:34)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/@cloudant/cloudant/cloudant.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Emitted 'error' event at:
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:42:14
    at callbackOrRejectError (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:47:12)
    at Object.fetchDocs [as fetch] (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/nano/lib/nano.js:649:16)
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:39:10
    at check (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2116:13)
    at doWhilst (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2119:16)
    at awaitable (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:208:32)
    at Object.doUntil (/usr/local/node/lib/node_modules/@cloudant/couchbackup/node_modules/async/dist/async.js:2147:16)
    at module.exports (/usr/local/node/lib/node_modules/@cloudant/couchbackup/includes/shallowbackup.js:28:9)
    at /usr/local/node/lib/node_modules/@cloudant/couchbackup/app.js:251:26
```

**Comment by bessbd** [comment]
The debug mode really doesn't seem to provide a lot of extra information right now. Just to see if we can do anything, what does the log file look like? Can you please share an anonymized excerpt? Also, what happens if you try a lower (maybe much lower) `bufferSize`?

**Comment by ricellis** [comment]
I think this is caused by a behaviour change upstream in Nano. It seems that 8.2.2 added [this additional (IMO invalid) check](https://github.com/apache/couchdb-nano/blob/6bf6efcca83412053aacf542b2e33192b4bc3f5f/lib/nano.js#L646) that the `POST` to `_all_docs` includes a body with a `keys` element. The server doesn't reject those requests so I don't see why Nano should.

**Comment by wyattmw** [comment]
I tried with a smaller buffer count (100), but there are only 386 docs in the database.  Failed the same way.  Buffer size doesn't seem like it would be an issue since the same command works with `--mode full` and the buffer size set to either 100 or 5000.

Seems to me like an issue checking the parameters (and only `--mode shallow`?) as it never gets to the point where it looks like it's pulling data from the db.

**Comment by bessbd** [comment]
> I tried with a smaller buffer count (100), but there are only 386 docs in the database. Failed the same way. Buffer size doesn't seem like it would be an issue since the same command works with `--mode full` and the buffer size set to either 100 or 5000.
> 
> Seems to me like an issue checking the parameters (and only `--mode shallow`?) as it never gets to the point where it looks like it's pulling data from the db.

Hi @wyattmw ,

If you are able, can you please try using `master` (with the recent change #340 of @ricellis )?
That should resolve the issue you're currently facing.

**Comment by ricellis** [comment]
We're doing some long running regression buckets, we'll release the fix ASAP.

**Comment by ricellis** [comment]
Version [2.6.0](https://github.com/cloudant/couchbackup/releases/tag/2.6.0) with the fix is now available.

**Comment by wyattmw** [comment]
I tested v2.6.0 and it seems to be working.  Will do some additional testing with our full backup process and if I find anything else I'll open another issue. Thank you all.

`]# /usr/local/node/bin/couchbackup --url https://xxx:xxx@wwwibmid-dal-nonprod.cloudant.com/ --buffer-size 100 --db ngapi_permissions_pre --mode shallow > test.out
================================================================================
Performing backup on https://****:****@wwwibmid-dal-nonprod.cloudant.com/ngapi_permissions_pre using configuration:
{
  "bufferSize": 100,
  "mode": "shallow",
  "requestTimeout": 120000
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Written batch ID: 0 Total document revisions written: 100 Time: 0.022 +166ms
  couchbackup:backup Written batch ID: 1 Total document revisions written: 200 Time: 0.044 +22ms
  couchbackup:backup Written batch ID: 2 Total document revisions written: 300 Time: 0.063 +19ms
  couchbackup:backup Written batch ID: 3 Total document revisions written: 387 Time: 0.082 +19ms
  couchbackup:backup Finished - Total document revisions written: 387 +0ms`
