### ISSUE TITLE
Memory leak when invoking backup for multiple databases

### ISSUE THREAD

**Issue by LyteFM** [cloudant/couchbackup#342]
## Bug Description

When using `couchbackup.backup` multiple times in a nodejs app, a memory leak occurs.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Simple Iterate over multiple databases and perform backups, e.g. via:

```js
const couchbackup = require("@cloudant/couchbackup");
const fs = require("fs");
const cloudant = require("@cloudant/cloudant");

function backupDatabase(dbName) {
  return new Promise((resolve, reject) => {
    const stream = fs.createWriteStream("data/" + dbName);
    couchbackup.backup(
      process.env.CLOUDANT_URL + dbName,
      stream,
      { iamApiKey: process.env.CLOUDANT_IAM_APIKEY },
      (err, obj) => {
        if (err) {
          console.log(err);
          reject(new Error("Couchbackup failed for db: " + dbName));
          return;
        }
        stream.end();
        console.log("Download from " + dbName + " complete.");
        resolve();
      }
    );
  });
}

async function couchBackupAction() {
  const dbList = await cloudant({
    url: process.env.CLOUDANT_URL,
    plugins: [{ iamauth: { iamApiKey: process.env.CLOUDANT_IAM_APIKEY } }]
  }).db.list();

  for (const dbName of dbList) {
    await backupDatabase(dbName);
  }
}

couchBackupAction();
```

### 2. What you expected to happen

All databases are backed up without excessive memory consumption.

### 3. What actually happened

With every additional database, the memory usage is growing and not enough memory can be freed by garbage collection. Depending on the available system memory, the process crashes at some point.

I've profiled the app with chrome devtools and noticed that:
- among the primitives, there were _a lot_ of identical `"access_token=..."` strings
- about the same number of `CloudantClient` as backed up databases and about double that amount of `EventEmitter` and `IAMTokenManager` were present

I've tried to manually unsubscribe from the `EventEmitter` returned by `couchbackup.backup`, but that didn't improve anything.
To me, it looks like a new `cloudant` - instance is instantiated when calling `backup` without allowing GC to free it up once the backup has completed.

## Environment details

| software | version|
| --- | --- |
|Node.js | 12.18.3|
|@cloudant/couchbackup | 2.5.2 |
|@cloudant/cloudant | 4.3.0 |

**Comment by emlaver** [comment]
@LyteFM thanks for reporting this! We'll look into it and get back to you as soon as possible.

**Comment by LyteFM** [comment]
I don't get any helpful errors, the process simply gets killed by the system or it stops when monitoring via chrome and setting a `--max_old_space` - value. 
The multiple `IAMTokenManagers` were the most striking Objects that existed more often and consumed more memory than expected, but here are some more screenshots comparing two runs after backing up a couple of 100 dbs, compared to the previous snapshot:

![Screenshot from 2020-10-15 13-52-01](https://user-images.githubusercontent.com/19202953/96263924-e6ca7780-0fc3-11eb-9817-fedfab2d0c2c.png)

![Screenshot from 2020-10-15 14-24-44](https://user-images.githubusercontent.com/19202953/96263872-d2867a80-0fc3-11eb-9c8f-f89576765a7a.png)

Or a single dump showing much usage via `Request` and `IAMTokenManager`:

![Screenshot from 2020-10-15 13-40-19](https://user-images.githubusercontent.com/19202953/96264068-18dbd980-0fc4-11eb-899a-86b3b51e940f.png)

whereas this screenshot was taken a few 100 DBs earlier:

![Screenshot from 2020-10-15 13-35-31](https://user-images.githubusercontent.com/19202953/96264155-301ac700-0fc4-11eb-9f58-309e559386fa.png)

**Comment by ricellis** [comment]
I'm going to close this as we've completely replaced the underlying client library from `@cloudant/cloudant` to `@ibm-cloud/cloudant` in the meantime and the new has a different HTTP client and a different IAM auth implementation.

Feel free to open a new issue If you see a similar problem using `2.7.0` or newer.
