### ISSUE TITLE
Couchbackup ERROR: Changes request terminated before last_seq was sent

### ISSUE THREAD

**Issue by markhewitt1978** [cloudant/couchbackup#343]
l
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Using Centos7 from command line. Installed via npm

[root@couchdb-staging ~]# couchbackup --db users > /archive/users.archive
================================================================================
Performing backup on http://****:****@localhost:5984/users using configuration:
{
  "bufferSize": 500,
  "log": "/tmp/tmp-5544-tWyb1POVZTZb",
  "mode": "full",
  "parallelism": 5,
  "requestTimeout": 120000,
  "resume": false
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Total batches received: 1 +660ms
  couchbackup:backup Total batches received: 2 +17ms
  couchbackup:backup Total batches received: 3 +10ms
  couchbackup:backup Total batches received: 4 +9ms
  couchbackup:backup Total batches received: 5 +19ms
  couchbackup:backup Total batches received: 6 +23ms
  couchbackup:backup Total batches received: 7 +10ms
  couchbackup:backup Total batches received: 8 +8ms
  couchbackup:backup Total batches received: 9 +26ms
  couchbackup:backup Total batches received: 10 +23ms
ERROR: Changes request terminated before last_seq was sent
[root@couchdb-staging ~]#

### 2. What you expected to happen

The backup to run to completion

### 3. What actually happened

The above error message

**Comment by mojito317** [comment]
Hi @markhewitt1978!

Could you run your command in log mode and share the results? E.g.:
```
couchbackup --log backup.log --url <URL> --db "users" > /archive/users.archive
```

Are not you running the backup on the `_users` db instead of `users`? If that is the case then this [workaround](on 12 Oct 2018) could help.

It would be also helpful if you could share the details of your environment, like:
* the version of couchbackup being used (`couchbackup --version`)
* the version of Node.js being used

**Comment by ricellis** [comment]
Closing as no additional information has been provided.

FWIW that error usually indicates that Couch hung up before finishing the changes response - improving couchbackup's behaviour in those situations is suggested by #100.
