### ISSUE TITLE
[Issue] ERROR: error happened in your connection DEPTH_ZERO_SELF_SIGNED_CERT self signed certificate

### ISSUE THREAD

**Issue by pdelteil** [cloudant/couchbackup#347]
## Bug Description
My server is self signed, this is the reason of the described error. 

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

1. Defined the required variables 
2. Ran ``couchbackup``

### 2. What you expected to happen
Create a dump of the database. 

### 3. What actually happened

```
================================================================================
Performing backup on https://****:****@domain.tld:port/bbrf using configuration:
{
  "bufferSize": 500,
  "log": "/tmp/tmp-17014-Z7GXsVucU730",
  "mode": "full",
  "parallelism": 5,
  "requestTimeout": 120000,
  "resume": false
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
ERROR: error happened in your connection DEPTH_ZERO_SELF_SIGNED_CERT self signed certificate

 ```

## Environment details
- Version(s) that are affected by this issue.
    > 2.6.0
- Node.js version
    > 8.10.0

**Comment by emlaver** [comment]
Hello @pdelteil, you will need to configure node.js to trust your self-signed certificate.  [Click here for details](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) on adding your own certification authority file.  Closing issue, please re-open if you have any additional questions.

**Comment by pdelteil** [comment]
> Hello @pdelteil, you will need to configure node.js to trust your self-signed certificate. [Click here for details](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) on adding your own certification authority file. Closing issue, please re-open if you have any additional questions.

Thanks. 

I only needed to set this variable:

``export NODE_TLS_REJECT_UNAUTHORIZED='0'``
