### ISSUE TITLE
Question about 

### ISSUE THREAD

**Issue by schwichti** [cloudant/couchbackup#349]
Hi. I simply have a question of understanding regarding a part from the documentation: https://www.npmjs.com/package/@cloudant/couchbackup#why-use-couchbackup.
> The easiest way to backup a CouchDB database is to copy the ".couch" file. This is fine on a single-node instance, but when running multi-node Cloudant or using CouchDB 2.0 or greater, the ".couch" file only contains a single shard of data. This utility allows simple backups of CouchDB or Cloudant database using the HTTP API.

Is that generally true for CouchDB 3 or does it depend on your individual cluster configuration? For example, when you have 3 cluster nodes and CouchDB settings are set to `n=3` and `q=2` (see https://docs.couchdb.org/en/latest/cluster/sharding.html), I'd expect that every single node in the cluster has all the data and you can copy the .couch files from any of these three nodes. When you have 6 nodes with `n=3` and `q=2` this approach does not work anymore and the above citation is true that every node has just a single shard. Please correct me if I am wrong.

**Comment by mojito317** [comment]
Hi @schwichti! 

It is true that the picture can be more complicated than that statement suggests, but there are additional complications around the consistency of shard replicas. I suggest you ask in [CouchDB slack](https://couchdb.slack.com
) or the [CouchDB users mailing list](https://lists.apache.org/list.html?user@couchdb.apache.org) if you want clarification on specifics of couch file internals.

**Comment by schwichti** [comment]
Thanks for the quick response. I will do that.
