### ISSUE TITLE
MaxListenersExceededWarning from backup() to a writeStream

### ISSUE THREAD

**Issue by frostmar** [cloudant/couchbackup#352]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
In a nodejs app backing up Cloudant databases to a writestream (in this case, a gzip stream from `zlib.createGzip()` piped to Cloud Object Storage) we see nodejs warnings `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [Gzip].`

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

I don't have time to cut down the code to a simple reproduction right now, but if that's really necessary I may be able to do so shortly.

### 2. What you expected to happen
No MaxListenersExceededWarning 

### 3. What actually happened

Using: @cloudant/couchbackup@2.3.0

in @cloudant/couchbackup/app.js line 273 I believe:
```js
          if (q && !q.isPaused) {
```
should be 
```js
          if (q && !q.paused) {
```

Because: In the debugger I can't see any property or accessor `q.isPaused` ... so it never understands when it's already paused, and many duplicate `drain` event handlers are added.

## Environment details
- Version(s) that are affected by this issue.
   @cloudant/couchbackup@2.3.0
- Node.js version
    v14.15.4

**Comment by bessbd** [comment]
The PR would certainly be helpful, @frostmar !
