### ISSUE TITLE
Restoration succeeds but no data restored

### ISSUE THREAD

**Issue by julienguillot77** [cloudant/couchbackup#367]
## Bug Description

Data is not restored whether using the library programmatically or CLI. 
Credentials are correct and restoration function returns successful result without any error.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

**CLI**

```
cat account.txt | couchrestore
================================================================================
Performing restore on https://****:****@842a0159-7858-4384-a61d-fdec510369db-bluemix.cloudant.com/account using configuration:
{
  "bufferSize": 500,
  "parallelism": 5,
  "requestTimeout": 120000
}
================================================================================
  couchbackup:restore restored 1 +0ms
  couchbackup:restore finished { total: 1 } +9ms
```

**Programmatically**

Get backup data from AWS S3 Bucket, create filestream from Body and call restore function.

```
const carryOutRestore = async (s3, fileName, date, callback) => {
    return new Promise((resolve) => {
        let fileStream = null;

        const Key = `${date}/${fileName}.txt`;

        s3.getObject({
            Bucket: process.env.AWS_S3_BUCKET,
            Key
        }, (err, data) => {
            if (err)
                return callback(Error(`[S3] File not found: ${db_name}.txt`));

            fileStream = Readable.from([data.Body.toString()])

            const uri = `https://${process.env.CLOUDANT_LOGIN}:${process.env.CLOUDANT_PASSWORD}@${process.env.CLOUDANT_ACCOUNT}-bluemix.cloudant.com/${fileName}`;

            if (fileStream) {
                couchbackup.restore(
                    fileStream,
                    uri,
                    { parallelism: 2 },
                    function (err, data) {
                        console.log({ data }) // Prints { total: 1 }
                        if (err) {
                            callback(Error({
                                status: 400,
                                message: "Error",
                                error: err
                            }));
                            return resolve();
                        }

                        callback(null, {
                            result: 'success',
                            status: 200,
                            message: "Successfuly restored backup.",
                        });
                        resolve();
                    });
            } else {
                callback(Error(`Stream is empty: ${db_name}`));
                resolve();
            }
        });
    })
}
```

### 2. What you expected to happen

1 document to be restored on the _account_ database.

### 3. What actually happened

No data restored on the _account_ database

## Environment details

- OS : MacOS Big Sur
- IDE : Visual Studio Code
- Version of couchbackup package : 2.6.1
- Node.js version(s) : 12.22.1 and 14.17.5

Database state screenshot and account test data attached on this ticket.

[account.txt](https://github.com/cloudant/couchbackup/files/7042717/account.txt)

<img width="1729" alt="Capture d’écran 2021-08-25 à 08 43 41" src="https://user-images.githubusercontent.com/26235609/130705389-0908b087-65f7-41c8-9c79-abd208aa45ce.png">

We are at your disposal for additional information.

Thanks in advance.

**Comment by ricellis** [comment]
>Originally there was 1 doc we deleted to test restoration

As per the [documentation](https://github.com/cloudant/couchbackup/#restore-1)
>It uploads that to a Cloudant database, which should be a **new** database.

The database you restore into should be a new database without any existing documents or revision history. Consider this example:
* Database `sccount` contains `doc1` at `1-abc`
* Backup performed and contains `doc1` at `1-abc`
* Delete `doc1`, now `account` database contains `doc1` [deleted] at rev `2-def`
* Restore into `account` database writes `doc1` at rev `1-abc`
* `2-def` the deleted rev of `doc1` is still the winning revision, so `doc1` does not appear to be present

This is why it is necessary to restore into a new database. Although it is present in the docs I think we could make that requirement more clear in the `README`.

**Comment by eiri** [comment]
All right, README was updated to put more emphasis on the requirements for a target database and there is new issue #376 to add a validation check into `restore` to make this part more explicit. Closing this issue now.
