### ISSUE TITLE
Add a preflight check for restore function to make sure that target database is new

### ISSUE THREAD

**Issue by eiri** [cloudant/couchbackup#376]
Couchbackup could benefit from a perflight check for restore functionality to confirm that a target database exists and is new , i.e. it has `doc_count` and `doc_del_count` in a database info set to `0`.

There seems to be a possibility of confusion on the requirements for a target database (ref: #367), so it'd make it a better user experience to have this part to be an explicit run error or at least a warning.

It looks like `includes/writer.js` is the right spot to add this functionality.

**Comment by ricellis** [comment]
The existing `HEAD` existence check is at https://github.com/cloudant/couchbackup/blob/c67e771fb8b9a44661fe608630f2c84c46d1c316/app.js#L163 and is used by both `backup` and `restore`.

For restore it is called here:
https://github.com/cloudant/couchbackup/blob/c67e771fb8b9a44661fe608630f2c84c46d1c316/app.js#L333

We can extend the check in `proceedIfDbValid` for the restore case.
