### ISSUE TITLE
bug: backup quetly exit with 0 when server side is dropping connection

### ISSUE THREAD

**Issue by eiri** [cloudant/couchbackup#527]
When server side drops connection mid-response backup stops on the last valid batch and exits with 0 without calling `on.('finished')` function.

The root cause is a bug in axios 0.x where client quietly drops response without raising 'connection abort' exception when response is compressed. e.g. header `Accept-Encoding` set to `gzip` or `*`.

This bug fixed in axios 1.x, but unfortunately we'd need for sdk-core to move on it first, then release new cloudant-sdk and only then get this fix in backup, which potentially looks like quite long wait.

Alternative approach could be to try to switch only backup to axios 1.x and force core to work with it, though this sounds like a typical node deps' hell.

Another alternative could be to detect and raise this condition in cloudant-sdk BaseService with axios response interceptor or event listener on a custom Agent. However this requires a spike to investigate how feasible it is.

**Comment by ricellis** [comment]
See #542

**Comment by ricellis** [comment]
This is fixed in [2.9.6](https://github.com/cloudant/couchbackup/releases/tag/2.9.6).
