### ISSUE TITLE
couchbackup and couchrestore results in ECONNREFUSED error

### ISSUE THREAD

**Issue by roswah** [cloudant/couchbackup#571]
### Steps to reproduce:
I have created a script that should backup from one database A and then restore database B.

The content of the script looks like this:

call curl -u [username]:[pwd] -X DELETE http://localhost:5984/[dbnameB]
call curl -u [username]:[pwd] -X PUT http://localhost:5984/[dbnameB]
call couchbackup --url http://[username]:[pwd]@localhost:5984 --db [dbnameA] --log D:\CouchDBRestore\logfile.log | couchrestore --url http://[username]:[pwd]@localhost:5984 --db [dbnameB]

So the script deletes database B, then creates an empty database B and then restores from database A to database B.

### 2. What I expect to happen:
The database B should have the same content as database A.

### 3. What actually happende:
The delete and put commando succeeded but the couchbackup commando fails with the following error message:
"ERROR: connect ECONNREFUSED ::1:5984: post http://localhost:5984/_session ECONNREFUSED"

Unfortunately the message does not say so much.

I have also tried to tear down the script to only contain the couchbackup-commando. But I still got the same error message.

## Environment details:
This script has been run daily for a couple of years now towards a CouchDB instance with version 2.3.1.
Now I have installed the newest version of CouchDB 3.3.1 on a windows server 2019 where Node.js 18.15.0 is installed.
CouchDB is running on a single node.
The two databases are on the same instance of CouchDB on the same machine. The script is also run on the same machine.
But the same script that has been run successfully for a couple of years now does not work anymore towards the newer version of CouchDB.

**Comment by emlaver** [comment]
Hello @roswah, what version of couchbackup are you using?

**Comment by emlaver** [comment]
Ok, I've managed to reproduce the same error under Node version 18.15.0 with latest couchbackup.  This error does not happen under v16.20.0.  I'm currently investigating and will update when I have more info.

**Comment by emlaver** [comment]
This issue is related to a change in Node v17: https://github.com/nodejs/node/issues/40537
The workaround is to use `127.0.0.1` instead of `localhost` in the `url`.

**Comment by roswah** [comment]
Thanks a lot for your quick help and investigation. Ok, so the problem is in Node. Well I am glad there is a work around and I will test it immediately.

**Comment by roswah** [comment]
And it worked! Thanks again. You saved me a lot of time and headache.
